name: Robot Framework Tests

on:
  push:
    branches: [ cinema-challenge ]
  pull_request:
    branches: [ cinema-challenge ]

jobs:
  robot:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependências do projeto Robot Framework
        run: |
          pip install -r robotfrontend/requirements.txt

      - name: Inicializar RF Browser
        run: |
          rfbrowser init

      - name: Instalar dependências do frontend
        run: |
          cd robotfrontend
          npm install

      - name: Iniciar o frontend com npm start (em background)
        run: |
          cd robotfrontend
          nohup npm start &

      - name: Aguardar frontend subir
        run: sleep 10

      - name: Executar testes Robot Framework
        run: |
          cd robotfrontend
          robot -d logs resources/**/signup.robot

      - name: Upload de logs de execução
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: robotfrontend/logs
