name: Robot Framework Tests

on:
  push:
    branches:
      - cinema-challenge
  pull_request:
    branches:
      - cinema-challenge

jobs:
  robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependências do projeto Robot Framework
        run: |
          pip install -r robotfrontend/requirements.txt

      - name: Inicializar RF Browser
        run: |
          rfbrowser init

      - name: Executar testes Robot Framework
        run: |
          robot -d logs robotfrontend/tests

      - name: Upload de logs de execução
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: logs/